version: "3.7"
services:
  otel:
    image: otel/opentelemetry-collector-contrib:latest
    command: --config /otel-collector/collector-config.yml --log-level debug
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - HOSTMETRICS_COLLECTION_INTERVAL_IN_SECONDS
      - LOG_GROUP_NAME
      - LOGS_NAMESPACE
      - LOG_STREAM_NAME
      - PROCESS_COMMAND_LINE
      - PROCESS_EXECUTABLE_NAME
    volumes:
      - ./otel-collector:/otel-collector
      - type: bind
        source: /proc
        target: /proc
    ports:
      - '4317:4317'
    user: "${UID}:${GID}"

  app:
    image: ${APP_IMAGE}
    environment:
      - INSTANCE_ID
      - LISTEN_ADDRESS
      - FLASK_LOG_LEVEL=ERROR
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION=us-west-2
      - OTEL_RESOURCE_ATTRIBUTES=service.name=aws-otel-integ-test
      - OTEL_EXPORTER_OTLP_ENDPOINT=grpc://otel:4317
    ports:
      - '8080:8080'

  load-generator:
    build:
      context: ./load-generator
    environment:
      - SOAK_TEST_DURATION_IN_MINUTES
    depends_on:
      - otel
      - app

  alarms-poller:
    build:
      context: ./alarms-poller
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION=us-west-2
      - HOSTMETRICS_COLLECTION_INTERVAL_IN_SECONDS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - load-generator

# # To run on Cloud Desktop:
# #
# version: "3.7"
# services:
#   otel:
#     image: otel/opentelemetry-collector-contrib:latest
#     command: --config /config/collector-config.yml --log-level debug
#     environment:
#       - LOG_GROUP_NAME=test
#       - LOGS_NAMESPACE=test
#       - LOG_STREAM_NAME=test
#       - HOSTMETRICS_COLLECTION_INTERVAL_IN_SECONDS=5s
#       - PROCESS_COMMAND_LINE="/usr/local/bin/python3 application.py"
#       - PROCESS_EXECUTABLE_NAME=python3
#     volumes:
#       - ./config:/config
#       - $HOME/.aws:/.aws
#       - type: bind
#         source: /proc
#         target: /proc
#     ports:
#       - '4317:4317'
#     privileged: true
#     user: "0:${GID}"
#     # user: "${UID}:${GID}"

#   app:
#     # image: ${APP_IMAGE}
#     image: ghcr.io/nathanielrn/aws-otel-python-soaking-tests-demo-sample-app-flask-auto-058adecda934295b3eb45e42d5bc9208b100492b:main
#     environment:
#       - INSTANCE_ID=test
#       - LISTEN_ADDRESS=0.0.0.0:8080
#       - FLASK_LOG_LEVEL=ERROR
#       - AWS_REGION=us-west-2
#       - OTEL_RESOURCE_ATTRIBUTES=service.name=aws-otel-integ-test
#       - OTEL_EXPORTER_OTLP_ENDPOINT=grpc://otel:4317
#     volumes:
#       - $HOME/.aws:/.aws
#     ports:
#       - '8080:8080'

#   load-generator:
#     build:
#       context: .
#     command: hey -z 30s http://app:8080/outgoing-http-call
#     depends_on:
#       - otel
#       - app
