name: Testing for Env Variables
on:
  push:
    branches: [ main ]

jobs:
  example_test:
    name: Testing what values exist
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
    steps:
      - name: What values exist?
        run: |
          echo ${{ github.repository }}
          echo ${{ github.repository_owner }}
          echo ${{ github.context.repo }}
          echo ${{ github.context.repo.repo }}
          echo ${{ github.context.repo.owner }}
      - name: Clone This Repo First
        uses: actions/checkout@v2
      - name: Publish Issue if failed AFTER Performance Tests
        uses: NathanielRN/create-an-issue@v2.5.1-alpha2
        env:
          APP_PLATFORM: TEST_APP_PLATFORM
          INSTRUMENTATION_TYPE: TEST_INSTRUMENTATION_TYPE
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: TEST_OKAY
        with:
          filename: .github/issue-templates/FAILURE-AFTER-SOAK_TESTS.md